namespace Bobail.AI.Analysis.Models;

public sealed record MatchupSummary(
    string MatchupName,
    string BotAName,
    string BotBName,
    string LeaderName,
    int TotalGames,
    int BotAWins,
    int BotBWins,
    int Draws,
    double BotAWinrate,
    double BotBWinrate,
    double LeaderWinrate,
    int BotAStartedGames,
    int BotAStartedWins,
    int BotBStartedGames,
    int BotBStartedWins,
    double BotAStartedWinrate,
    double BotBStartedWinrate,
    double AverageTurns,
    int MinTurns,
    int MaxTurns,
    double OneSidedLeaderPValue,
    bool StatisticallySignificant);
